version: 2.1
workflows:
  version: 2
  build-and-push:
    jobs:
      - build-and-push
jobs:
  build-and-push:
    machine:
      image: ubuntu-2004:current
    environment:
      DOCKER_IMAGE: vblaas/chuckci
      DOCKER_TAG: latest
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            python3 -m pytest
      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKER_IMAGE:$DOCKER_TAG . 
      - run:
          name: Login to DockerHub
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $TOKEN_DOCKER
      - run:
          name: Run and Curl APP
          command: |
            docker run -d -p 8080:8080 $DOCKER_IMAGE:$DOCKER_TAG
            sleep 10
            curl 127.0.0.1:8080
       
      - run:
          name: Push Docker Image to DockerHub
          command: |
            docker push $DOCKER_IMAGE:$DOCKER_TAG
