name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: envCI # Spécifie l'environnement
    env:
      DOCKER_IMAGE: vblaas/chuckci
      DOCKER_TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment AND Run tests
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          python3 -m pytest
      
      - name: Log in to DockerHub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          TOKEN_DOCKER: ${{ secrets.TOKEN_DOCKER }}
        run: echo "$TOKEN_DOCKER" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        
      - name: Build Docker image
        run: |
          docker build -t $DOCKER_IMAGE:$DOCKER_TAG .

      - name: Run Docker container and test application
        run: |
          docker run -d -p 8000:8000 $DOCKER_IMAGE:$DOCKER_TAG
          sleep 60
          curl 127.0.0.1:8000
          

      - name: Push Docker image to DockerHub
        run: |
          docker push $DOCKER_IMAGE:$DOCKER_TAG

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Ce token est généré automatiquement par GitHub Actions
        with:
          tag_name: ${{ github.ref_name }} # Utilise uniquement le nom du tag (par exemple, "v1.0.0")
          release_name: Release ${{ github.ref_name }} # Nom de la release
          body: |
            Changes in this Release
          draft: false
          prerelease: false
